### ISSUE TITLE
No messages appearing on PRs despite re-installation

### ISSUE THREAD

**Issue by desilinguist** [pep8speaks-org/pep8speaks#184] opened 2020-09-29 14:25 UTC
We are no longer receiving any comments on our PRs in our public [repository](https://github.com/EducationalTestingService/rsmtool). It used to work perfectly a few months ago when we did our last release. I uninstalled the app an reinstalled it via the marketplace but that didn't change anything. I checked our `.pep8speaks.yml` file and it's still there and correctly formatted. Any help figuring this out would be greatly appreciated! We really love the functionality that pep8speaks provides – it makes things so much easier for us.

**Comment by OrkoHunter** [comment] 2020-09-29 19:06
Hey @desilinguist, thank you for creating the issue and using pep8speaks. :)

The service seems to be up since the latest public comment was [few minutes ago](https://github.com/rrosajp/plugin.video.xstream/pull/38#issuecomment-700910665). :)

I doubt that GitHub is not sending payloads from the repository. Can you please check again how the app is installed? Have you installed it on a few repos, or all the repos, and if that is on your personal account or on the `EducationalTestingService` org? Screenshots might help me.

I can then manually mock a payload from the repository for a Pull Request and see if there are any technical issues.

**Comment by desilinguist** [comment] 2020-09-29 19:13
Hi @OrkoHunter ! Thank you so much for the prompt reply. It's much appreciated.

Originally, I had installed pep8speaks outside of the GitHub marketplace. However, this morning, since it wasn't working, I uninstalled it and reinstalled it from inside the marketplace. I installed it in the EducationalTestingService organization and gave it access to the couple of repos that we use it with. Below are the two screenshots that show this. Please let me know if you need anything else.

<img width="1043" alt="Screen Shot 2020-09-29 at 3 08 17 PM" src="https://user-images.githubusercontent.com/161680/94604803-2f64ff80-0266-11eb-8286-41d970e9135c.png">

<img width="1032" alt="Screen Shot 2020-09-29 at 3 08 51 PM" src="https://user-images.githubusercontent.com/161680/94604829-3855d100-0266-11eb-9559-2ecb5002bb52.png">

**Comment by OrkoHunter** [comment] 2020-09-30 06:55
In my test PR [here](https://github.com/EducationalTestingService/rsmtool/pull/473), I manually mocked the payload which GitHub is supposed to send to PEP8Speaks server. That resulted in an expected comment.

So, the problem here is that GitHub is not sending payloads for the repository. I will look into it more.

**Comment by desilinguist** [comment] 2020-09-30 11:34
Thank you so much for looking into this!

________________________________

**Comment by dalmia** [comment] 2021-01-23 09:45
Any updates on this? @OrkoHunter 
We are also facing the same issue as you mentioned. Looking forward to your comment. Thank you for building `pep8speaks` :)

**Comment by OrkoHunter** [comment] 2021-01-23 12:10
Hello @dalmia ! Thank you :) I have been looking into this issue on and off again with no success.

Could you help out with some details?

- Which repositor(y/ies) did you install the GitHub app on?
- Have you not seen a pep8speaks comment on _any_ PRs?

Thanks!

**Comment by dalmia** [comment] 2021-01-23 12:36
Thanks for getting back so quickly, @OrkoHunter! :)

- Unfortunately, it is a private repository that we intend to open-source soon!
- No, we haven't seen any pep8speaks comment on any PR - we installed it 2 weeks ago!

Can you share a mock payload as you have used above to replicate and confirm that this is indeed the issue for us too? Also, any reason that this would work for one service (your first comment in this thread) and not for another one?

**Comment by OrkoHunter** [comment] 2021-01-24 16:42
Hey @dalmia ! @pep8speaks by default does not work with private repos since the bot needs access to comment. This issue is about the bot not commenting on a public repo.

See this for more details https://github.com/orkohunter/pep8speaks#private-repos

https://gist.github.com/OrkoHunter/8bdbba46327df13ce3f89e6dcbdfa59c This is a mock payload I use to test against a local PEP8Speaks server.

**Comment by dalmia** [comment] 2021-01-26 12:00
Thanks for clarifying that and providing the link to the guidelines for a private repo, @OrkoHunter!

**Comment by carterbox** [comment] 2021-02-05 18:55
I stopped receiving comments on my public repo from pep8speaks [sometime in November of 2020](https://github.com/tomography/tike/pull/101). Are there any debugging/troubleshooting steps I can follow?

**Comment by desilinguist** [comment] 2021-02-05 18:56
This has still not worked for us and we have switched to using [pre-commit](https://pre-commit.com) hooks instead.

**Comment by OrkoHunter** [comment] 2021-02-05 19:59
@carterbox Thanks for the link to the issue, I can reproduce a payload from GitHub to see if something is wrong with the server or whether GitHub has stopped sending payloads in some settings.

Meanwhile, the pep8speaks is still actively commenting on a lot of the PRs out there. (last one being 2 hours ago) https://github.com/search?o=desc&q=commenter%3Apep8speaks&s=created&type=Issues

@desilinguist pre-commits are awesome and I use them too! Appreciate you sharing it here. :)

**Comment by OrkoHunter** [comment] 2021-02-05 20:06
@carterbox I simulated a GitHub payload for the PR https://github.com/tomography/tike/pull/101 and sent it to the server, and the bot updated the comment.

![Screenshot 2021-02-05 at 21 03 38](https://user-images.githubusercontent.com/8065913/107083268-ab172000-67f5-11eb-9479-1924a0064970.png)

I am not sure what's going on with automated payloads from GitHub. Let me create a test PR on your repository and verify whether a payload is being sent or not. Thanks!

**Comment by OrkoHunter** [comment] 2021-02-05 20:14
Huh, I created a new PR and the bot commented. https://github.com/tomography/tike/pull/120

@carterbox PEP8Speaks will not comment on a PR if there are no errors. You can change this behavior by setting `no_blank_comment: False` in `.pep8speaks.yml` https://github.com/orkohunter/pep8speaks#configuration

**Comment by carterbox** [comment] 2021-02-05 20:18
@OrkoHunter, I didn't expect that the default option was to be silent without errors! Thanks for your help debugging this for me! I guess pep8speaks has trained my contributors to lint their own code!

**Comment by OrkoHunter** [comment] 2021-02-05 20:21
Closing this issue since the original author has moved away. To new users: feel free to open a new issue with details, and I'll help out!

**Closed as completed by OrkoHunter** 2021-02-05 20:21 UTC
Labels: bug
